import Head from "next/head";
import { SSRProvider } from "react-bootstrap";
import Affix from "../../components/Affix";
import FireworkCanvas from "../../components/FireworkCanvas";
import NavLink from "../../components/NavLink";

function Docs() {
  return (
    <SSRProvider>
      <div className=" tw-select-none ">
        <FireworkCanvas />
        <Head>
          <title>张宇腾 My Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="min-h-screen tw-mx-auto tw-grid tw-grid-flow-col tw-grid-cols-4 tw-subpixel-antialiased">
          <div className=" tw-col-start-1 tw-col-end-2 tw-bg-white tw-px-5 tw-min-h-screen"></div>
          <div className=" tw-col-start-2 tw-col-end-4 tw-border-l tw-border-r">
            <Affix direction={"top"} space={0}>
              <nav className=" tw-flex tw-justify-center tw-py-2 tw-border-b tw-bg-white">
                <NavLink content={"Home"} checked={false} href="/" />
                <NavLink content={"Docs"} checked={true} href="/docs" />
                <NavLink content={"About"} checked={false} href="about" />
              </nav>
            </Affix>
          </div>
          <div className="tw-pt-4 tw-col-start-4 tw-col-end-5 tw-px-5 "></div>
        </main>
      </div>
    </SSRProvider>
  );
}

export default Docs;
