import { AsyncThunkAction } from "@reduxjs/toolkit";
import classNames from "classnames";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { Button, SSRProvider } from "react-bootstrap";
import { useSelector } from "react-redux";
import { fetchFilterTagsData, fetchPinnedListData } from "../../api-ajax/SSR-ajax";
import Affix from "../../components/Affix";
import FireworkCanvas from "../../components/FireworkCanvas";
import NavLink from "../../components/NavLink";
import { PinnedListModel } from "../../model/PinnedListModel";
import {
  cleanList,
  DocsCheckerFilter,
  DocsCheckerState,
  fetchCheckedDocsList,
  selectCheckerState
} from "../../slices/DocsCheckerSlice";
import CheckBroad from "../../views/CheckBroad";
import DocsList from "../../views/DocsList";
import Header from "../../views/HeaderLOGO";
import PinnedListBroad from "../../views/PinnedList";
import { useAppDispatch } from "../_store";

function Docs(props: { fetchedFilterTagsData: string[]; fetchedPinnedListData: PinnedListModel }) {
  const checker_state = useSelector<DocsCheckerState, DocsCheckerState>(selectCheckerState);
  const dispatch = useAppDispatch();
  const handleLoadMore = () => {
    console.log(checker_state.filter.tags);
    
    dispatch(
      fetchCheckedDocsList({
        tags: checker_state.filter.tags,
        keyword: checker_state.filter.keyword,
        outset: checker_state.list[checker_state.list.length - 1].postDate,
      })
    );
    console.log(checker_state.list[checker_state.list.length - 1].postDate);
  };

  return (
    <SSRProvider>
      <div className=" tw-select-none ">
        <FireworkCanvas />
        <Head>
          <title>张宇腾MyBlog-归档</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Affix direction={"top"} space={0}>
          <nav className=" tw-flex tw-justify-center tw-py-2 tw-border-b tw-bg-white">
            <NavLink content={"Home"} checked={false} href="/" />
            <NavLink content={"Docs"} checked={true} href="/docs" />
            <NavLink content={"About"} checked={false} href="about" />
          </nav>
        </Affix>
        <main
          className={classNames(
            "tw-min-h-screen",
            "tw-mx-auto",
            "tw-grid",
            "tw-grid-cols-1",
            "tw-grid-flow-row",
            "lg:tw-grid-cols-4",
            "tw-subpixel-antialiased"
          )}
        >
          <div className={classNames("tw-col-span-1", "lg:tw-col-span-1", "tw-px-5")}>
            <header className=" tw-mt-6">
              <Header />
            </header>
            <Affix direction={"top"} space={90}>
              <CheckBroad tags={props.fetchedFilterTagsData} />
            </Affix>
          </div>
          <div
            className={classNames(
              "tw-col-span-1",
              "lg:tw-col-span-2",
              "tw-border-l",
              "tw-border-r"
            )}
          >
            <DocsList list={checker_state.list} />
            <div className=" tw-my-4 tw-flex tw-justify-center">
              <Button className="shadow-none" as="div" onClick={handleLoadMore}>
                {"加载更多"}
              </Button>
            </div>
          </div>
          <div
            className={classNames(
              "tw-col-span-1",
              "md:tw-col-span-3",
              "lg:tw-col-span-1",
              "tw-px-5"
            )}
          >
            <Affix direction={"top"} space={90}>
              <PinnedListBroad list={props.fetchedPinnedListData} />
            </Affix>
          </div>
        </main>
      </div>
    </SSRProvider>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      fetchedFilterTagsData: (await fetchFilterTagsData()).data,
      fetchedPinnedListData: (await fetchPinnedListData()).data,
    },
  };
};

export default Docs;
function dispatch(
  arg0: AsyncThunkAction<{ list: any; filter: DocsCheckerFilter }, DocsCheckerFilter, {}>
) {
  throw new Error("Function not implemented.");
}
