import AboutMe from "../views/AboutMe";
import Affix from "../components/Affix";
import DocsList from "../views/DocsList";
import FireworkCanvas from "../components/FireworkCanvas";
import Friends from "../views/Friends";
import Head from "next/head";
import Header from "../views/Header";
import OfficeInfo from "../views/OfficeInfo";
import PinAndCheckCard from "../views/PinAndCheckCard";
import SocialBlock from "../views/SocialBlock";
import { AboutMeModel } from "../model/AboutMeModel";
import { DocsListModel } from "../model/DocsListModel";
import {
  fetchAboutmeData,
  fetchDocsListData,
  fetchFilterTagsData,
  fetchFriendListData,
  fetchOfficeInfoData,
  fetchPinnedListData,
} from "../SSR-ajax";
import { FriendListModel } from "../model/FriendListModel";
import { OfficeInfoModel } from "../model/OfficeInfoModel";
import { PinnedListModel } from "../model/PinnedListModel";
import { SSRProvider } from "react-bootstrap";
import type { GetServerSideProps } from "next";

function Home(props: {
  fetchedAboutmeData: AboutMeModel;
  fetchedPinnedListData: PinnedListModel;
  fetchedFriendListData: FriendListModel;
  fetchedOfficeInfoData: OfficeInfoModel;
  fetchedDocsListData: DocsListModel;
  fetchedFilterTagsData: string[];
}) {
  return (
    <SSRProvider>
      <div className=" tw-select-none ">
        <FireworkCanvas />
        <Head>
          <title>张宇腾 My Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="min-h-screen tw-mx-auto tw-grid tw-grid-flow-col tw-grid-cols-4 tw-subpixel-antialiased">
          <div className=" tw-col-start-1 tw-col-end-2 tw-bg-white tw-px-5 tw-min-h-screen">
            <Header />
            <AboutMe
              avatarURL={props.fetchedAboutmeData.avatarURL}
              impression={props.fetchedAboutmeData.impression}
              badges={props.fetchedAboutmeData.badges}
              quote={props.fetchedAboutmeData.quote}
            />
            <Affix direction="top" space={50}>
              <PinAndCheckCard
                pinnedList={props.fetchedPinnedListData}
                filterTags={props.fetchedFilterTagsData}
              />
            </Affix>
          </div>
          <div className=" tw-col-start-2 tw-col-end-4 tw-border-l tw-border-r">
            <DocsList list={props.fetchedDocsListData} />
          </div>
          <div className="tw-pt-4 tw-col-start-4 tw-col-end-5 tw-px-5 ">
            <Friends list={props.fetchedFriendListData} />
            <OfficeInfo
              icp={props.fetchedOfficeInfoData.icp}
              siteTitle={props.fetchedOfficeInfoData.siteTitle}
              icpa={props.fetchedOfficeInfoData.icpa}
              ps={props.fetchedOfficeInfoData.ps}
              copyright={props.fetchedOfficeInfoData.copyright}
              poweredBy={props.fetchedOfficeInfoData.poweredBy}
              position={props.fetchedOfficeInfoData.position}
              phoneCall={props.fetchedOfficeInfoData.phoneCall}
              email={props.fetchedOfficeInfoData.email}
            />
            <Affix direction="top" space={50}>
              <SocialBlock />
            </Affix>
          </div>
        </main>
      </div>
    </SSRProvider>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      fetchedAboutmeData: (await fetchAboutmeData()).data,
      fetchedPinnedListData: (await fetchPinnedListData()).data,
      fetchedFriendListData: (await fetchFriendListData()).data,
      fetchedOfficeInfoData: (await fetchOfficeInfoData()).data,
      fetchedDocsListData: (await fetchDocsListData()).data,
      fetchedFilterTagsData: (await fetchFilterTagsData()).data,
    },
  };
};

export default Home;
